from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from backend.models.user import UserRole, User
from backend.models.employee import Employee
from backend.api.deps import RoleChecker, get_current_active_user, get_db
from backend.schemas.hr import CreateEmployeeSchema, CreateEmployeeResponse
from backend.core.security import get_password_hash
import uuid
import secrets
import string

router = APIRouter()

allow_hr = RoleChecker([UserRole.HR])

def generate_employee_login_id(db: Session, full_name: str, year: int) -> str:
    # Format: OI + 2 letters first name + 2 letters last name + year + 4 digit serial
    # Example: OIJODO20220001
    names = full_name.strip().split()
    if len(names) >= 2:
        f = names[0][:2].upper()
        l = names[-1][:2].upper()
    elif len(names) == 1:
        f = names[0][:2].upper()
        l = "XX" 
    else:
        f = "XX"
        l = "XX"
        
    base_prefix = f"OI{f}{l}{year}"
    
    # Count existing users with this prefix
    # Note: This simple count might collision if we have deletions, but for this scope it's okay.
    # Ideally find max serial.
    existing_count = db.query(User).filter(User.login_id.like(f"{base_prefix}%")).count()
    serial = existing_count + 1
    
    return f"{base_prefix}{serial:04d}"

def generate_temp_password(length=10):
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for i in range(length))

@router.post("/create-employee", response_model=CreateEmployeeResponse, dependencies=[Depends(allow_hr)])
def create_employee(
    emp_data: CreateEmployeeSchema,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
):
    # Check if email exists in User table
    if db.query(User).filter(User.email == emp_data.email).first():
        raise HTTPException(status_code=400, detail="Email already registered")
        
    # Check if phone exists (Employee table)
    # Note: Since Employee is linked to User, checking User.email covers Auth. 
    # But checking Employee.phone is duplicate check for profile.
    if db.query(Employee).filter(Employee.phone == emp_data.phone).first():
        raise HTTPException(status_code=400, detail="Phone number already registered")

    # Generate Login ID
    emp_login_id = generate_employee_login_id(db, emp_data.full_name, emp_data.joining_year)
    
    # Ensure login ID is unique
    if db.query(User).filter(User.login_id == emp_login_id).first():
       emp_login_id = emp_login_id[:-4] + f"{int(emp_login_id[-4:]) + 1:04d}"

    temp_password = generate_temp_password()
    
    try:
        # 1. Create User (Auth)
        new_user = User(
            # public_id generated by default
            email=emp_data.email,
            login_id=emp_login_id,
            password_hash=get_password_hash(temp_password),
            role=UserRole.EMPLOYEE,
            must_change_password=True,
            is_active=True
        )
        db.add(new_user)
        db.flush() # Flush to get new_user.id for FK
        
        # 2. Create Employee (Profile)
        new_employee = Employee(
            # public_id generated by default
            user_id=new_user.id,
            created_by_id=current_user.id,
            employee_code=emp_login_id, # Using login_id as code for now
            full_name=emp_data.full_name,
            department=emp_data.department,
            job_title=emp_data.job_title,
            date_of_joining=emp_data.joining_date,
            phone=emp_data.phone,
            address=emp_data.address,
            profile_picture_url=None
        )
        db.add(new_employee)
        db.commit()
        db.refresh(new_employee)
        
        return {
            "message": "Employee Created Successfully",
            "employee_login_id": emp_login_id,
            "temporary_password": temp_password,
            "public_id": new_employee.public_id
        }
        
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))
